version: 2.1

executors:
  node-16:
    docker:
      - image: cimg/node:16.14.0-browsers

jobs:
  install:
    executor: node-16
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/
          paths:
            - ./
  build:
    executor: node-16
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn build-test
      - persist_to_workspace:
          root: ~/
          paths:
            - ./
  lint:
    executor: node-16
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn lint
  test:
    executor: node-16
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn coverage
  cypress:
    executor: node-16
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn cypress:ci
      - store_artifacts:
          path: ./cypress/videos
      - store_artifacts:
          path: ./cypress/screenshots


workflows:
  default-deploy:
    jobs:
      - install:
          context: global
      - build:
          context: global
          requires:
            - install
      - lint:
          context: global
          requires:
            - install
      - test:
          context: global
          requires:
            - install
      - cypress:
          context: global
          requires:
            - build
